### ISSUE TITLE
ImportError: cannot import name UserList - on deploy

### ISSUE THREAD

**Issue by ghost** [Bun/mail#1]
Hi there,

on running the deploy script on Alpine linux 3.8.0 i get 

Traceback (most recent call last):
  File "./bin/jinja-render", line 4, in <module>
    from collections import UserList
ImportError: cannot import name UserList

What happend?

Best regards

**Comment by Bun** [comment]
Looks like your default Python is Python 2, which doesn't have UserList.

**Comment by ghost** [comment]
Thanks!
